[project]
name = "rag-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kha2", email = "hoge" }
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "psycopg2-binary>=2.9.12",
]

[project.scripts]
rag-exp = "rag_exp:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
